In [1]:
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
from pandas import Series,DataFrame
import statsmodels
import statsmodels.api as sm
import statsmodels.formula.api as smf
import scipy.stats
import scipy.optimize
import scipy.spatial
from IPython import display
from ipywidgets import interact ,widgets
import scipy.stats as stats
import math

In [2]:
from sklearn.datasets import load_wine

In [3]:
wine=load_wine()

In [4]:
X=wine.data
y=wine.target

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.30)

# LOGISTIC REGRESSION #

In [7]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()

In [8]:
lr.fit(X_train,y_train)

D:\anaconda\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
D:\anaconda\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [9]:
lr.score(X_test,y_test)

0.9629629629629629

In [10]:
y_predicted=lr.predict(X_test)
from sklearn.metrics import confusion_matrix

In [11]:
cm=confusion_matrix(y_test,y_predicted)

In [12]:
cm

array([[17,  0,  0],
       [ 0, 22,  1],
       [ 0,  1, 13]], dtype=int64)

In [13]:
FP = cm.sum(axis=0) - np.diag(cm)  
FN = cm.sum(axis=1) - np.diag(cm)
TP = np.diag(cm)
TN = cm.sum() - (FP + FN + TP)

# Sensitivity, hit rate, recall, or true positive rate
TPR = TP/(TP+FN)
# Specificity or true negative rate
TNR = TN/(TN+FP) 
# Precision or positive predictive value
PPV = TP/(TP+FP)
# Negative predictive value
NPV = TN/(TN+FN)
# Fall out or false positive rate
FPR = FP/(FP+TN)
# False negative rate
FNR = FN/(TP+FN)
# False discovery rate
FDR = FP/(TP+FP)

# Overall accuracy
ACC = (TP+TN)/(TP+FP+FN+TN)
print(FP,FN,TP,TN)

[0 1 1] [0 1 1] [17 22 13] [37 30 39]


In [14]:
n=len(FP)

In [15]:
M=[]
for i in range(0,n):
    M.append(FP[i]+TP[i])
print(M)

[17, 23, 14]


In [16]:
M=[]
for i in range(0,n):
    M.append(FP[i]+TP[i])
print(M)

[17, 23, 14]


In [17]:
d01=pd.DataFrame(FP,columns=['logisticregfp'])

In [18]:
d02=pd.DataFrame(TP,columns=['logisticregtp'])
d03=pd.DataFrame(y_predicted,columns=['prd'])

# DECISION TREE #

In [19]:
from sklearn import tree
model=tree.DecisionTreeClassifier()

In [20]:
model.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [21]:
model.score(X_test,y_test)

0.8333333333333334

In [22]:
y_predicted=model.predict(X_test)

In [23]:
cm=confusion_matrix(y_test,y_predicted)

In [24]:
FP = cm.sum(axis=0) - np.diag(cm)  
FN = cm.sum(axis=1) - np.diag(cm)
TP = np.diag(cm)
TN = cm.sum() - (FP + FN + TP)

# Sensitivity, hit rate, recall, or true positive rate
TPR = TP/(TP+FN)
# Specificity or true negative rate
TNR = TN/(TN+FP) 
# Precision or positive predictive value
PPV = TP/(TP+FP)
# Negative predictive value
NPV = TN/(TN+FN)
# Fall out or false positive rate
FPR = FP/(FP+TN)
# False negative rate
FNR = FN/(TP+FN)
# False discovery rate
FDR = FP/(TP+FP)

# Overall accuracy
ACC = (TP+TN)/(TP+FP+FN+TN)
print(FP,FN,TP,TN)

[1 7 1] [2 2 5] [15 21  9] [36 24 39]


In [25]:
n=len(FP)

In [26]:
M=[]
for i in range(0,n):
    M.append(FP[i]+TP[i])
print(M)

[16, 28, 10]


In [27]:
d1=pd.DataFrame(M,columns=['decisiontree'])

In [28]:
d11=pd.DataFrame(FP,columns=['decisiontreefp'])

In [29]:
d12=pd.DataFrame(TP,columns=['decisiontreetp'])
d13=pd.DataFrame(y_predicted,columns=['prd'])

# KNN #

In [30]:
from sklearn.neighbors import KNeighborsClassifier

In [31]:
knn=KNeighborsClassifier(n_neighbors=5)

In [32]:
knn.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [33]:
knn.score(X_test,y_test)

0.7407407407407407

In [34]:
y_predicted=knn.predict(X_test)

In [35]:
cm=confusion_matrix(y_test,y_predicted)

In [36]:
FP = cm.sum(axis=0) - np.diag(cm)  
FN = cm.sum(axis=1) - np.diag(cm)
TP = np.diag(cm)
TN = cm.sum() - (FP + FN + TP)

# Sensitivity, hit rate, recall, or true positive rate
TPR = TP/(TP+FN)
# Specificity or true negative rate
TNR = TN/(TN+FP) 
# Precision or positive predictive value
PPV = TP/(TP+FP)
# Negative predictive value
NPV = TN/(TN+FN)
# Fall out or false positive rate
FPR = FP/(FP+TN)
# False negative rate
FNR = FN/(TP+FN)
# False discovery rate
FDR = FP/(TP+FP)

# Overall accuracy
ACC = (TP+TN)/(TP+FP+FN+TN)
print(FP,FN,TP,TN)

[5 4 5] [1 6 7] [16 17  7] [32 27 35]


In [37]:
M=[]
for i in range(0,n):
    M.append(FP[i]+TP[i])
print(M)

[21, 21, 12]


In [38]:
d2=pd.DataFrame(M,columns=['knn'])

In [39]:
d21=pd.DataFrame(FP,columns=['knnfp'])

In [40]:
d22=pd.DataFrame(TP,columns=['knntp'])
d23=pd.DataFrame(y_predicted,columns=['prd'])

# RANDOM FOREST #

In [41]:
from sklearn.ensemble import RandomForestClassifier

In [42]:
model=RandomForestClassifier(n_estimators=35)

In [43]:
model.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=35, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [44]:
y_predicted=model.predict(X_test)

In [45]:
model.score(X_test,y_test)

0.9814814814814815

In [46]:
cm=confusion_matrix(y_test,y_predicted)

In [47]:
FP = cm.sum(axis=0) - np.diag(cm)  
FN = cm.sum(axis=1) - np.diag(cm)
TP = np.diag(cm)
TN = cm.sum() - (FP + FN + TP)

# Sensitivity, hit rate, recall, or true positive rate
TPR = TP/(TP+FN)
# Specificity or true negative rate
TNR = TN/(TN+FP) 
# Precision or positive predictive value
PPV = TP/(TP+FP)
# Negative predictive value
NPV = TN/(TN+FN)
# Fall out or false positive rate
FPR = FP/(FP+TN)
# False negative rate
FNR = FN/(TP+FN)
# False discovery rate
FDR = FP/(TP+FP)

# Overall accuracy
ACC = (TP+TN)/(TP+FP+FN+TN)
print(FP,FN,TP,TN)

[1 0 0] [0 1 0] [17 22 14] [36 31 40]


In [48]:
M=[]
for i in range(0,n):
    M.append(FP[i]+TP[i])
print(M)

[18, 22, 14]


In [49]:
d3=pd.DataFrame(M,columns=['rf'])

In [50]:
d31=pd.DataFrame(FP,columns=['rffp'])

In [51]:
d32=pd.DataFrame(TP,columns=['rftp'])
d33=pd.DataFrame(y_predicted,columns=['prd'])

# SUPPORT VECTOR MACHINE #

In [52]:
from sklearn.svm import SVC

In [53]:
model=SVC(gamma='scale')
model.fit(X_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [54]:
y_predicted=model.predict(X_test)

In [55]:
model.score(X_test,y_test)

0.6851851851851852

In [56]:
cm=confusion_matrix(y_test,y_predicted)

In [57]:
FP = cm.sum(axis=0) - np.diag(cm)  
FN = cm.sum(axis=1) - np.diag(cm)
TP = np.diag(cm)
TN = cm.sum() - (FP + FN + TP)

# Sensitivity, hit rate, recall, or true positive rate
TPR = TP/(TP+FN)
# Specificity or true negative rate
TNR = TN/(TN+FP) 
# Precision or positive predictive value
PPV = TP/(TP+FP)
# Negative predictive value
NPV = TN/(TN+FN)
# Fall out or false positive rate
FPR = FP/(FP+TN)
# False negative rate
FNR = FN/(TP+FN)
# False discovery rate
FDR = FP/(TP+FP)

# Overall accuracy
ACC = (TP+TN)/(TP+FP+FN+TN)
print(FP,FN,TP,TN)

[ 4 13  0] [ 2  1 14] [15 22  0] [33 18 40]


D:\anaconda\lib\site-packages\ipykernel_launcher.py:11: RuntimeWarning: invalid value encountered in true_divide
  # This is added back by InteractiveShellApp.init_path()
D:\anaconda\lib\site-packages\ipykernel_launcher.py:19: RuntimeWarning: invalid value encountered in true_divide


In [58]:
M=[]
for i in range(0,n):
    M.append(FP[i]+TP[i])
print(M)

[19, 35, 0]


In [59]:
d4=pd.DataFrame(M,columns=['svm'])
d41=pd.DataFrame(FP,columns=['svmfp'])
d42=pd.DataFrame(TP,columns=['svmtp'])

# MLP #

In [60]:
from sklearn.neural_network import MLPClassifier

In [61]:
mlp=MLPClassifier(random_state=37)

In [62]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train_scaled=scaler.fit(X_train).transform(X_train)
X_test_scaled=scaler.fit(X_test).transform(X_test)
mlp=MLPClassifier(max_iter=1000,random_state=42)
mlp.fit(X_train_scaled,y_train)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=1000, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=42, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)

In [63]:
mlp.score(X_test_scaled,y_test)

0.9629629629629629

In [64]:
y_predicted=mlp.predict(X_test)

In [65]:
cm=confusion_matrix(y_test,y_predicted)

In [66]:
FP = cm.sum(axis=0) - np.diag(cm)  
FN = cm.sum(axis=1) - np.diag(cm)
TP = np.diag(cm)
TN = cm.sum() - (FP + FN + TP)

# Sensitivity, hit rate, recall, or true positive rate
TPR = TP/(TP+FN)
# Specificity or true negative rate
TNR = TN/(TN+FP) 
# Precision or positive predictive value
PPV = TP/(TP+FP)
# Negative predictive value
NPV = TN/(TN+FN)
# Fall out or false positive rate
FPR = FP/(FP+TN)
# False negative rate
FNR = FN/(TP+FN)
# False discovery rate
FDR = FP/(TP+FP)

# Overall accuracy
ACC = (TP+TN)/(TP+FP+FN+TN)
print(FP,FN,TP,TN)

[37  0  0] [ 0 23 14] [17  0  0] [ 0 31 40]


D:\anaconda\lib\site-packages\ipykernel_launcher.py:11: RuntimeWarning: invalid value encountered in true_divide
  # This is added back by InteractiveShellApp.init_path()
D:\anaconda\lib\site-packages\ipykernel_launcher.py:13: RuntimeWarning: invalid value encountered in true_divide
  del sys.path[0]
D:\anaconda\lib\site-packages\ipykernel_launcher.py:19: RuntimeWarning: invalid value encountered in true_divide


In [67]:
M=[]
for i in range(0,n):
    M.append(FP[i]+TP[i])
print(M)

[54, 0, 0]


In [68]:
d5=pd.DataFrame(M,columns=['mlp'])
d51=pd.DataFrame(FP,columns=['mlpfp'])
d52=pd.DataFrame(TP,columns=['mlptp'])

# NAIVE BAYS #

In [69]:
import sklearn
from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics

In [70]:
bnb=BernoulliNB(binarize=0.1)
bnb.fit(X_train,y_train)
bnb.score(X_test,y_test)

0.42592592592592593

In [71]:
y_predicted=bnb.predict(X_test)

In [72]:
cm=confusion_matrix(y_test,y_predicted)

In [73]:
FP = cm.sum(axis=0) - np.diag(cm)  
FN = cm.sum(axis=1) - np.diag(cm)
TP = np.diag(cm)
TN = cm.sum() - (FP + FN + TP)

# Sensitivity, hit rate, recall, or true positive rate
TPR = TP/(TP+FN)
# Specificity or true negative rate
TNR = TN/(TN+FP) 
# Precision or positive predictive value
PPV = TP/(TP+FP)
# Negative predictive value
NPV = TN/(TN+FN)
# Fall out or false positive rate
FPR = FP/(FP+TN)
# False negative rate
FNR = FN/(TP+FN)
# False discovery rate
FDR = FP/(TP+FP)

# Overall accuracy
ACC = (TP+TN)/(TP+FP+FN+TN)
print(FP,FN,TP,TN)

[ 0 31  0] [17  0 14] [ 0 23  0] [37  0 40]


D:\anaconda\lib\site-packages\ipykernel_launcher.py:11: RuntimeWarning: invalid value encountered in true_divide
  # This is added back by InteractiveShellApp.init_path()
D:\anaconda\lib\site-packages\ipykernel_launcher.py:13: RuntimeWarning: invalid value encountered in true_divide
  del sys.path[0]
D:\anaconda\lib\site-packages\ipykernel_launcher.py:19: RuntimeWarning: invalid value encountered in true_divide


In [74]:
M=[]
for i in range(0,n):
    M.append(FP[i]+TP[i])
print(M)

[0, 54, 0]


In [75]:
d6=pd.DataFrame(M,columns=['bnb'])
d61=pd.DataFrame(FP,columns=['bnbfp'])
d62=pd.DataFrame(TP,columns=['bnbtp'])
d63=pd.DataFrame(y_predicted,columns=['prd'])

In [76]:
mnb=MultinomialNB()
mnb.fit(X_train,y_train)
mnb.score(X_test,y_test)

0.9259259259259259

In [77]:
y_predicted=mnb.predict(X_test)

In [78]:
cm=confusion_matrix(y_test,y_predicted)

In [79]:
FP = cm.sum(axis=0) - np.diag(cm)  
FN = cm.sum(axis=1) - np.diag(cm)
TP = np.diag(cm)
TN = cm.sum() - (FP + FN + TP)

# Sensitivity, hit rate, recall, or true positive rate
TPR = TP/(TP+FN)
# Specificity or true negative rate
TNR = TN/(TN+FP) 
# Precision or positive predictive value
PPV = TP/(TP+FP)
# Negative predictive value
NPV = TN/(TN+FN)
# Fall out or false positive rate
FPR = FP/(FP+TN)
# False negative rate
FNR = FN/(TP+FN)
# False discovery rate
FDR = FP/(TP+FP)

# Overall accuracy
ACC = (TP+TN)/(TP+FP+FN+TN)
print(FP,FN,TP,TN)

[1 2 1] [2 0 2] [15 23 12] [36 29 39]


In [80]:
M=[]
for i in range(0,n):
    M.append(FP[i]+TP[i])
print(M)

[16, 25, 13]


In [81]:
d7=pd.DataFrame(M,columns=['mnb'])
d71=pd.DataFrame(FP,columns=['mnbfp'])
d72=pd.DataFrame(TP,columns=['mnbtp'])
d73=pd.DataFrame(y_predicted,columns=['prd'])

In [82]:
 gnb=GaussianNB()
gnb.fit(X_train,y_train)
gnb.score(X_test,y_test)

1.0

In [83]:
y_predicted=gnb.predict(X_test)

In [84]:
cm=confusion_matrix(y_test,y_predicted)

In [85]:
FP = cm.sum(axis=0) - np.diag(cm)  
FN = cm.sum(axis=1) - np.diag(cm)
TP = np.diag(cm)
TN = cm.sum() - (FP + FN + TP)

# Sensitivity, hit rate, recall, or true positive rate
TPR = TP/(TP+FN)
# Specificity or true negative rate
TNR = TN/(TN+FP) 
# Precision or positive predictive value
PPV = TP/(TP+FP)
# Negative predictive value
NPV = TN/(TN+FN)
# Fall out or false positive rate
FPR = FP/(FP+TN)
# False negative rate
FNR = FN/(TP+FN)
# False discovery rate
FDR = FP/(TP+FP)

# Overall accuracy
ACC = (TP+TN)/(TP+FP+FN+TN)
print(FP,FN,TP,TN)

[0 0 0] [0 0 0] [17 23 14] [37 31 40]
