In [15]:
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
from pandas import Series,DataFrame
import statsmodels
import statsmodels.api as sm
import statsmodels.formula.api as smf
import scipy.stats
import scipy.optimize
import scipy.spatial
from IPython import display
from ipywidgets import interact ,widgets
import scipy.stats as stats
import math
from sklearn.metrics import accuracy_score, recall_score, f1_score, roc_auc_score, make_scorer

In [16]:
from sklearn.datasets import load_breast_cancer

In [17]:
cancer=load_breast_cancer()

In [18]:
X=cancer.data
y=cancer.target

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.30)

# LOGISTIC REGRESSION #

In [21]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()

In [22]:
lr.fit(X_train,y_train)

D:\anaconda\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [23]:
lr.score(X_test,y_test)

0.9649122807017544

In [24]:
y_predicted=lr.predict(X_test)
from sklearn.metrics import confusion_matrix

In [25]:
cm=confusion_matrix(y_test,y_predicted)

In [26]:
cm

array([[ 62,   2],
       [  4, 103]], dtype=int64)

In [27]:
FP = cm.sum(axis=0) - np.diag(cm)  
FN = cm.sum(axis=1) - np.diag(cm)
TP = np.diag(cm)
TN = cm.sum() - (FP + FN + TP)

# Sensitivity, hit rate, recall, or true positive rate
TPR = TP/(TP+FN)
# Specificity or true negative rate
TNR = TN/(TN+FP) 
# Precision or positive predictive value
PPV = TP/(TP+FP)
# Negative predictive value
NPV = TN/(TN+FN)
# Fall out or false positive rate
FPR = FP/(FP+TN)
# False negative rate
FNR = FN/(TP+FN)
# False discovery rate
FDR = FP/(TP+FP)

# Overall accuracy
ACC = (TP+TN)/(TP+FP+FN+TN)
print(FP,FN,TP,TN)

[4 2] [2 4] [ 62 103] [103  62]


In [28]:
roc_auc_score(y_test,y_predicted)

0.9656834112149533

In [14]:
n=len(FP)

In [105]:
M=[]
for i in range(0,n):
    M.append(FP[i]+TP[i])
print(M)

[62, 109]


In [106]:
M=[]
for i in range(0,n):
    M.append(FP[i]+TP[i])
print(M)

[62, 109]


In [107]:
d01=pd.DataFrame(FP,columns=['logisticregfp'])

In [108]:
d02=pd.DataFrame(TP,columns=['logisticregtp'])
d03=pd.DataFrame(y_predicted,columns=['prd'])

# DECISION  TREE #

In [109]:
from sklearn import tree
model=tree.DecisionTreeClassifier()

In [110]:
model.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [111]:
model.score(X_test,y_test)

0.9005847953216374

In [112]:
y_predicted=model.predict(X_test)

In [113]:
cm=confusion_matrix(y_test,y_predicted)

In [114]:
cm

array([[59,  6],
       [11, 95]], dtype=int64)

In [115]:
cm

array([[59,  6],
       [11, 95]], dtype=int64)

In [116]:
FP = cm.sum(axis=0) - np.diag(cm)  
FN = cm.sum(axis=1) - np.diag(cm)
TP = np.diag(cm)
TN = cm.sum() - (FP + FN + TP)

# Sensitivity, hit rate, recall, or true positive rate
TPR = TP/(TP+FN)
# Specificity or true negative rate
TNR = TN/(TN+FP) 
# Precision or positive predictive value
PPV = TP/(TP+FP)
# Negative predictive value
NPV = TN/(TN+FN)
# Fall out or false positive rate
FPR = FP/(FP+TN)
# False negative rate
FNR = FN/(TP+FN)
# False discovery rate
FDR = FP/(TP+FP)

# Overall accuracy
ACC = (TP+TN)/(TP+FP+FN+TN)
print(FP,FN,TP,TN)

[11  6] [ 6 11] [59 95] [95 59]


In [117]:
n=len(FP)

In [118]:
M=[]
for i in range(0,n):
    M.append(FP[i]+TP[i])
print(M)

[70, 101]


In [119]:
d1=pd.DataFrame(M,columns=['decisiontree'])

In [120]:
d11=pd.DataFrame(FP,columns=['decisiontreefp'])

In [121]:
d12=pd.DataFrame(TP,columns=['decisiontreetp'])
d13=pd.DataFrame(y_predicted,columns=['prd'])

# KNN(7) #

In [122]:
from sklearn.neighbors import KNeighborsClassifier

In [123]:
knn=KNeighborsClassifier(n_neighbors=7)

In [124]:
knn.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=7, p=2,
           weights='uniform')

In [125]:
knn.score(X_test,y_test)

0.9239766081871345

In [126]:
y_predicted=knn.predict(X_test)

In [127]:
cm=confusion_matrix(y_test,y_predicted)

In [128]:
cm

array([[ 55,  10],
       [  3, 103]], dtype=int64)

In [129]:
FP = cm.sum(axis=0) - np.diag(cm)  
FN = cm.sum(axis=1) - np.diag(cm)
TP = np.diag(cm)
TN = cm.sum() - (FP + FN + TP)

# Sensitivity, hit rate, recall, or true positive rate
TPR = TP/(TP+FN)
# Specificity or true negative rate
TNR = TN/(TN+FP) 
# Precision or positive predictive value
PPV = TP/(TP+FP)
# Negative predictive value
NPV = TN/(TN+FN)
# Fall out or false positive rate
FPR = FP/(FP+TN)
# False negative rate
FNR = FN/(TP+FN)
# False discovery rate
FDR = FP/(TP+FP)

# Overall accuracy
ACC = (TP+TN)/(TP+FP+FN+TN)
print(FP,FN,TP,TN)

[ 3 10] [10  3] [ 55 103] [103  55]


In [130]:
n=len(FP)

In [131]:
M=[]
for i in range(0,n):
    M.append(FP[i]+TP[i])
print(M)

[58, 113]


In [132]:
d2=pd.DataFrame(M,columns=['knn'])

In [133]:
d21=pd.DataFrame(FP,columns=['knnfp'])

In [134]:
d22=pd.DataFrame(TP,columns=['knntp'])
d23=pd.DataFrame(y_predicted,columns=['prd'])

# RANDOM FOREST #

In [135]:
from sklearn.ensemble import RandomForestClassifier

In [136]:
model=RandomForestClassifier(n_estimators=35)

In [137]:
model.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=35, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [138]:
y_predicted=model.predict(X_test)

In [139]:
model.score(X_test,y_test)

0.9532163742690059

In [140]:
cm=confusion_matrix(y_test,y_predicted)

In [141]:
cm

array([[ 61,   4],
       [  4, 102]], dtype=int64)

In [142]:
FP = cm.sum(axis=0) - np.diag(cm)  
FN = cm.sum(axis=1) - np.diag(cm)
TP = np.diag(cm)
TN = cm.sum() - (FP + FN + TP)

# Sensitivity, hit rate, recall, or true positive rate
TPR = TP/(TP+FN)
# Specificity or true negative rate
TNR = TN/(TN+FP) 
# Precision or positive predictive value
PPV = TP/(TP+FP)
# Negative predictive value
NPV = TN/(TN+FN)
# Fall out or false positive rate
FPR = FP/(FP+TN)
# False negative rate
FNR = FN/(TP+FN)
# False discovery rate
FDR = FP/(TP+FP)

# Overall accuracy
ACC = (TP+TN)/(TP+FP+FN+TN)
print(FP,FN,TP,TN)

[4 4] [4 4] [ 61 102] [102  61]


In [143]:
n=len(FP)

In [144]:
M=[]
for i in range(0,n):
    M.append(FP[i]+TP[i])
print(M)

[65, 106]


In [145]:
d3=pd.DataFrame(M,columns=['rf'])

In [146]:
d31=pd.DataFrame(FP,columns=['rffp'])

In [147]:
d32=pd.DataFrame(TP,columns=['rftp'])
d33=pd.DataFrame(y_predicted,columns=['prd'])

# SUPPORT  VECTOR  MACHINE #


In [148]:
from sklearn.svm import SVC

In [149]:
model=SVC()
model.fit(X_train,y_train)

D:\anaconda\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [150]:
y_predicted=model.predict(X_test)

In [151]:
model.score(X_test,y_test)

0.6198830409356725

In [152]:
cm=confusion_matrix(y_test,y_predicted)

In [153]:
cm

array([[  0,  65],
       [  0, 106]], dtype=int64)

In [154]:
FP = cm.sum(axis=0) - np.diag(cm)  
FN = cm.sum(axis=1) - np.diag(cm)
TP = np.diag(cm)
TN = cm.sum() - (FP + FN + TP)

# Sensitivity, hit rate, recall, or true positive rate
TPR = TP/(TP+FN)
# Specificity or true negative rate
TNR = TN/(TN+FP) 
# Precision or positive predictive value
PPV = TP/(TP+FP)
# Negative predictive value
NPV = TN/(TN+FN)
# Fall out or false positive rate
FPR = FP/(FP+TN)
# False negative rate
FNR = FN/(TP+FN)
# False discovery rate
FDR = FP/(TP+FP)

# Overall accuracy
ACC = (TP+TN)/(TP+FP+FN+TN)
print(FP,FN,TP,TN)

[ 0 65] [65  0] [  0 106] [106   0]


D:\anaconda\lib\site-packages\ipykernel_launcher.py:11: RuntimeWarning: invalid value encountered in true_divide
  # This is added back by InteractiveShellApp.init_path()
D:\anaconda\lib\site-packages\ipykernel_launcher.py:13: RuntimeWarning: invalid value encountered in true_divide
  del sys.path[0]
D:\anaconda\lib\site-packages\ipykernel_launcher.py:19: RuntimeWarning: invalid value encountered in true_divide


In [155]:
n=len(FP)

In [156]:
M=[]
for i in range(0,n):
    M.append(FP[i]+TP[i])
print(M)

[0, 171]


In [157]:
d4=pd.DataFrame(M,columns=['svm'])

In [158]:
d41=pd.DataFrame(FP,columns=['svmfp'])

In [159]:
d42=pd.DataFrame(TP,columns=['svmtp'])
d43=pd.DataFrame(y_predicted,columns=['prd'])

# FISHER-EXACT  TEST #

In [163]:
contingency_table=pd.crosstab(d03["prd"],d13["prd"])
print('contingency_table :-\n',contingency_table)

contingency_table :-
 prd   0    1
prd         
0    70    0
1     0  101


In [164]:
oddsratio, pvalue = stats.fisher_exact(contingency_table)

In [165]:
print(pvalue)

9.098126248782898e-50


In [166]:
if(pvalue<0.05):
    print("reject null hypothesis")
else:
    print("reject alternate hypothesis")

reject null hypothesis
